# Generated by Django 5.2.18 on 2026-10-08 20:20

import apps.catalog.validators
import django.core.validators
import django.db.models.deletion
import re
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
                ('label', models.CharField(max_length=40)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('sale_price', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
                ('collections', models.ManyToManyField(blank=True, related_name='products', to='catalog.collection')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=80)),
                ('hex_color', models.CharField(blank=True, max_length=7, validators=[apps.catalog.validators.validate_hex_color])),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='catalog.product')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(max_length=500, unique=True, validators=[apps.catalog.validators.validate_storage_key])),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('width', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('height', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('content_type', models.CharField(choices=[('image/webp', 'image/webp')], default='image/webp', max_length=50)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.colorvariant')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VariantSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_sizes', to='catalog.size')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='catalog.colorvariant')),
            ],
            options={
                'ordering': ['size__position', 'size_id'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active', '-created_at'], name='product_cat_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='product_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__isnull', True), models.Q(('sale_price__gt', 0), ('sale_price__lt', models.F('price'))), _connector='OR'), name='product_sale_price_valid'),
        ),
        migrations.AddConstraint(
            model_name='colorvariant',
            constraint=models.UniqueConstraint(fields=('product', 'slug'), name='colorvariant_unique_product_slug'),
        ),
        migrations.AddConstraint(
            model_name='variantimage',
            constraint=models.UniqueConstraint(fields=('variant', 'position'), name='variantimage_unique_variant_position'),
        ),
        migrations.AddConstraint(
            model_name='variantimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('variant',), name='variantimage_one_primary_per_variant'),
        ),
        migrations.AddConstraint(
            model_name='variantimage',
            constraint=models.CheckConstraint(condition=models.Q(('width__gt', 0), ('height__gt', 0)), name='variantimage_dimensions_positive'),
        ),
        migrations.AddConstraint(
            model_name='variantimage',
            constraint=models.CheckConstraint(condition=models.Q(('content_type__in', ('image/webp',))), name='variantimage_content_type_allowed'),
        ),
        migrations.AddConstraint(
            model_name='variantsize',
            constraint=models.UniqueConstraint(fields=('variant', 'size'), name='variantsize_unique_variant_size'),
        ),
    ]
